apiVersion: apps/v1
kind: Deployment                          # type of object we are creating, here we are creating of type "Deployment"
metadata:                                 # Details about above Object - "Deployment"
  name:   myapp-deployment              # name of above object - "Deployment"


spec:                                     # specification of "Deployment" object 
  replicas: 1                             # 3 pods will be created by "Deployment" config
  
  selector: 
    matchLabels:
      component: microservice-myapp        # key to match with pod -> line number: 17 
  
  template:                               # template is the configuration of pods - Pod Template 
    
    metadata: 
      labels: 
        component: microservice-myapp     # key to map with "Service" object in this case it is "LoadBalancer" type service
    
    spec:                                 # specification of Pod
      containers:                         #container configuration
        - name: myapp-container
          image: ravisaditya/myapp
          ports: 
            - containerPort: 9090
                
   
        
      